const tasksArray = [
  {
    title: 'Wake up',
    description: 'get out of bed and brush your teeth and face',
    // date: '2023-06-08',
    priority: 'Medium',
    project: '',
    day: '',
    month: '',
    year: '',
  },
  {
    title: 'Breakfast',
    description: '125g of oats and 20g of almonds',
    // date: '2023-06-08',
    priority: 'High',
    project: '',
    day: '',
    month: '',
    year: '',
  },
  {
    title: 'Go grocery shopping',
    description: 'Buy milk, eggs, and bread',
    // date: '2023-06-08',
    priority: 'Medium',
    project: '',
    day: '',
    month: '',
    year: '',
  },
  {
    title: 'Clean the house',
    description: 'Vacuum, wash dishes',
    // date: '2023-06-10',
    priority: 'Low',
    project: '',
    day: '',
    month: '',
    year: '',
  },
  {
    title: 'Prepare the presentation',
    description: 'Gather data, create slides',
    // date: '2023-06-12',
    priority: 'High',
    project: '',
    day: '',
    month: '',
    year: '',
  },
  {
    title: 'Exercise',
    description: 'Run for 30 minutes',
    // date: '2023-06-07',
    priority: 'Medium',
    project: '',
    day: '',
    month: '',
    year: '',
  },
  {
    title: 'Call the dentist',
    description: 'Schedule an appointment',
    // date: '2023-06-09',
    priority: 'Low',
    project: '',
    day: '',
    month: '',
    year: '',
  },
  {
    title: 'Pay the bills',
    description: 'Electricity, water, gas',
    // date: '2023-06-15',
    priority: 'Medium',
    project: '',
    day: '',
    month: '',
    year: '',
  },
  {
    title: 'Study for the exam',
    description: 'Read chapter 5',
    // date: '2023-06-13',
    priority: 'High',
    project: '',
    day: '',
    month: '',
    year: '',
  },
  {
    title: 'Organize the trip',
    description: 'Book hotel, buy tickets',
    // date: '2023-06-20',
    priority: 'Low',
    project: '',
    day: '',
    month: '',
    year: '',
  },
];

export default tasksArray;
